#  _   _ _      ___  ____     ____             __ _                       _   _             
# | \ | (_)_  _/ _ \/ ___|   / ___|___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __  
# |  \| | \ \/ / | | \___ \  | |   / _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \ 
# | |\  | |>  <| |_| |___) | | |__| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
# |_| \_|_/_/\_\\___/|____/   \____\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                                                    |___/                                  
# ==========================================================================================
#  Standalone NixOS Configuration optimized for running Antigravity 2.0 / Electron IDEs
#  inside Apple's native Virtualization.framework window.
# ==========================================================================================

{ config, lib, pkgs, ... }:

{
  # =========================================================================
  #  1. IMPORTS & SYSTEM LEVEL DEFINITIONS
  # =========================================================================
  imports = [
    # Will be auto-generated by nixos-generate-config during VM installation
    ./hardware-configuration.nix
  ];

  # =========================================================================
  #  2. UEFI BOOTLOADER CONFIGURATIONS (ARM64 VIRTUAL FIRMWARE)
  # =========================================================================
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 0; # Bypass bootloader menu for faster boot times

  # =========================================================================
  #  3. KERNEL PARAMS & DIAGNOSTIC SILENCING
  # =========================================================================
  # Suppress USB LPM, TPM, and other hypervisor-specific logging on the console
  # and accelerate early terminal rendering.
  boot.kernelParams = [
    "quiet"                       # Suppress noisy kernel startup logs
    "loglevel=3"                  # Only show errors and warnings (hides informational/diagnostic noise)
    "systemd.show_status=auto"    # Keep status outputs clean and tidy
    "rd.systemd.show_status=false" # Suppress early Stage-1 initrd systemd status logging
    "rd.udev.log_level=3"         # Suppress verbose udev logging in initrd
  ];

  # =========================================================================
  #  4. KERNEL MODULE SLIMMING (DRIVER OVERHEAD REMOVAL)
  # =========================================================================
  # Blacklist hypervisor modules and unused hardware drivers that are built 
  # dynamically but do not exist in Apple's Virtualization.framework.
  boot.blacklistedKernelModules = [
    "megasas"         # LSI MegaRAID SAS controller (we boot via virtio_blk)
    "sdhci_pltfm"     # SD controller platform wrapper
    "sdhci"           # SD controller core
    "e1000e"          # Intel network driver (we use virtio_net)
    "e1000"           # Legacy Intel network driver
    "igb"             # Intel Gigabit driver
    "hv_vmbus"        # Hyper-V bus interface (redundant under Apple Silicon)
    "hyperv_keyboard" # Hyper-V keyboard interface
  ];

  # Restrict early Stage-1 initrd modules strictly to VirtIO essentials
  boot.initrd.availableKernelModules = [
    "virtio_pci"      # VirtIO PCI interface wrapper (essential to find devices)
    "virtio_blk"      # Block device driver (essential to mount root)
    "virtio_net"      # Network virtual adapter driver
    "virtio_console"  # Early serial boot logs output
    "xhci_pci"        # USB XHCI PCI driver (essential for mouse/keyboard inputs)
  ];

  # Fast LZ4 Ramdisk Decompression
  # Shifting to LZ4 enables order-of-magnitude faster decompression during early hypervisor booting
  boot.initrd.compressor = "${pkgs.lz4.out}/bin/lz4";

  # =========================================================================
  #  5. FILE SYSTEMS & PERSTISTENT MOUNT CONFIGURATION
  # =========================================================================
  # Disable file access time writes (noatime) on disk mounts to reduce 
  # physical SSD write wear on the Mac host.
  # Note: The 'discard' option has been removed from options here to prevent 
  # synchronous online discard from fragmenting the host's sparse disk file.
  fileSystems."/" = {
    options = [ "noatime" "nodiratime" "errors=remount-ro" ];
  };

  # Automatically mount the host shared workspace via VirtIO-FS on boot
  # 'nofail' prevents booting blockages if the shared folder is not attached.
  fileSystems."/home/nixos/shared" = {
    device = "shared";
    fsType = "virtiofs";
    options = [ "nofail" "defaults" ];
  };

  # =========================================================================
  #  6. NETWORKING & HYPERVISOR WORKAROUNDS
  # =========================================================================
  networking.hostName = "antigravity-nixos";
  networking.networkmanager.enable = true;
  networking.useDHCP = lib.mkForce true;

  # --- CRITICAL WORKAROUND: Chromium BPF IPv6 Socket Kernel Panic ---
  # Launching Chromium/Electron apps (like Antigravity) inside a guest VM
  # can trigger sudden kernel panics (null pointer dereferences) in systemd BPF socket
  # filters (`__cgroup_bpf_run_filter_skb`) due to IPv6 stack interactions. 
  # Completely disabling IPv6 globally and at the kernel level is strictly required.
  networking.enableIPv6 = false;
  boot.kernel.sysctl = {
    "net.ipv6.conf.all.disable_ipv6" = 1;
    "net.ipv6.conf.default.disable_ipv6" = 1;
    "net.ipv6.conf.lo.disable_ipv6" = 1;
    "net.core.bpf_jit_enable" = 0; # Disable BPF JIT to prevent kernel NULL pointer dereferences in sk_filter_trim_cap
  };

  # --- CRITICAL WORKAROUND: ADC Metadata Server & TCP Checksum Offload ---
  # 1. Local ADC Metadata Server Connection Timeouts:
  #    Go/Electron applications checking credentials locally will stall for exactly 
  #    42+ seconds trying to reach Google Cloud metadata at 169.254.169.254 if the network 
  #    doesn't explicitly reject the packet. This delay exceeds Electron's 30-second window 
  #    load timeout and causes a persistent "black screen" on startup. Adding an unreachable 
  #    route forces these checks to fail instantly (< 1ms).
  systemd.services.adc-metadata-blocker = {
    description = "Add unreachable route for Google Cloud Metadata IP to prevent ADC timeouts";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.iproute2}/bin/ip route replace unreachable 169.254.169.254";
      ExecStop = "-${pkgs.iproute2}/bin/ip route del unreachable 169.254.169.254";
    };
  };

  # 2. TCP Checksum Offloading and MTU Bugs:
  #    Apple's Virtualization.framework NAT gateway fails to process guest hardware-checksum-offloaded 
  #    TCP packets correctly, leading to silent download corruptions. Forcing software checksum 
  #    processing via 'ethtool -K dev rx off tx off' combined with an MTU limit of 1400 restores 
  #    complete network and packet integrity. We use a declarative NetworkManager dispatcher script
  #    to reliably apply these fixes when interfaces transition to the 'up' state.
  networking.networkmanager.dispatcherScripts = [
    {
      source = pkgs.writeText "disable-checksum-offload" ''
        #!/usr/bin/env bash
        interface="$1"
        action="$2"
        if [ "$action" = "up" ] && [ "$interface" != "lo" ]; then
          ${pkgs.ethtool}/bin/ethtool -K "$interface" rx off tx off 2>/dev/null || true
          ${pkgs.iproute2}/bin/ip link set dev "$interface" mtu 1400 2>/dev/null || true
        fi
      '';
    }
  ];

  # =========================================================================
  #  7. LOCALE, KEYBOARD & DISPLAY MANANGER
  # =========================================================================
  time.timeZone = "Europe/Amsterdam";
  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "us";

  # Enable high-performance 3D graphics hardware acceleration via VirtIO-GPU / VirGL
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      mesa
      virglrenderer
    ];
  };

  # Enable systemd-resolved for modern event-driven DNS resolution
  services.resolved.enable = true;

  # Enable the SPICE Guest Agent (Crucial for clipboard sharing & auto window resizing)
  services.spice-vdagentd.enable = true;

  # Setup standard dbus service (required by Electron/Chromium for notifications, theme sync, etc.)
  services.dbus.enable = true;

  # Enable the X11 windowing system and the XFCE Desktop Environment
  services.xserver = {
    enable = true;
    desktopManager = {
      xterm.enable = false;
      xfce.enable = true;
    };
    displayManager = {
      lightdm.enable = true;
    };
  };

  # Configure automatic login as user 'nixos'
  services.displayManager.autoLogin = {
    enable = true;
    user = "nixos";
  };

  # =========================================================================
  #  8. SECURITY, USERS & SUDO PRIVILEGES
  # =========================================================================
  # Setup user 'nixos' with passwordless sudo access for simple VM management
  users.users.nixos = {
    isNormalUser = true;
    extraGroups = [ "wheel" "video" "networkmanager" ];
    initialPassword = "nixos";
  };
  security.sudo.wheelNeedsPassword = false;

  # =========================================================================
  #  9. SYSTEM PACKAGES & RUNTIME DEPENDENCIES
  # =========================================================================
  # Install essential system utilities and library dependencies required by Electron, Chromium, 
  # and Antigravity 2.0 to boot without shared library panics.
  environment.systemPackages = with pkgs; [
    # Core system tools
    git
    go
    python3
    curl
    wget
    nano
    chromium
    pciutils
    glib

    # Lightweight GUI essentials
    xfce4-clipman-plugin
  ];

  # =========================================================================
  #  10. NIX PACKAGE MANAGER & GARBAGE COLLECTION TUNING
  # =========================================================================
  # Nix package manager tuning and resource safety limits
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    cores = 2;      # Allow dual-thread compilation for faster rebuilds on 4-vCPU guest
    max-jobs = 1;   # Limit parallel jobs to further reduce memory/CPU thrashing
    auto-optimise-store = true; # Automatically hardlink identical files in the store to save host SSD space
  };
  nixpkgs.config.allowUnfree = true;

  # Automatic weekly garbage collection to keep the VM clean and lightweight
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 7d";
  };

  # Disable legacy dhcpcd since we use NetworkManager's modern internal DHCP client
  networking.dhcpcd.enable = false;

  # Disable Wi-Fi scanning and wpa_supplicant completely (only Ethernet exists in VM)
  systemd.services.wpa_supplicant.enable = false;

  # =========================================================================
  #  11. DISC TRIMMING TIMER SERVICE (VM STORAGE HEALTH)
  # =========================================================================
  # Enable weekly fstrim.timer to reclaim unused virtual blocks asynchronously.
  # This is much more performant and secure than synchronous online discarding (the 'discard' mount option),
  # which causes severe fragmentation on host's sparse disk files.
  services.fstrim = {
    enable = true;
    interval = "weekly";
  };

  # =========================================================================
  #  12. SWAP SPACE CONFIGURATION
  # =========================================================================
  # Swap space configuration (Crucial safety valve for 4GB RAM guest VM)
  swapDevices = [ {
    device = "/var/lib/swapfile";
    size = 4096; # 4GB swap space
  } ];

  # =========================================================================
  #  13. PERFORMANCE, DOCUMENTATION & COMPATIBILITY LAYER
  # =========================================================================
  documentation.enable = false;
  documentation.nixos.enable = false;
  programs.command-not-found.enable = false;

  # Nix LD compatibility layer to allow running unpatched binary executables
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      glib
      gtk3
      nss
      nspr
      atk
      at-spi2-atk
      dbus
      cups
      libdrm
      libsecret
      mesa
      pango
      cairo
      alsa-lib
      systemd
      libxshmfence
      libgudev
      libx11
      libxcomposite
      libxcursor
      libxdamage
      libxext
      libxfixes
      libxi
      libxrandr
      libxrender
      libxtst
      libxcb
      libgbm
      expat
      libxkbcommon
      at-spi2-core
    ];
  };

  # =========================================================================
  #  14. SERVICES CONFIGURATION
  # =========================================================================
  # Enable the OpenSSH daemon for host-to-guest ssh access
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;
      PermitRootLogin = "yes";
    };
  };

  system.stateVersion = "26.05";
}
